name: 🐞 Bug
description: File a bug/issue
title: "Bug title"
labels: ["Bug", "Needs Triage"]
body:
- type: dropdown
  attributes:
    label: Status
    description: Set the current status of the issue.
    options:
      -  Open
      -  Partially Fixed
      -  Resolved
  validations:
    required: true
- type: dropdown
  attributes:
    label: Severity
    description: Set the current severity of the issue.
    options:
      -  Blocker
      -  High
      -  Medium
      -  Low
  validations:
    required: true
- type: dropdown
  attributes:
    label: WCAG
    multiple: true
    description: WCAG Success Criteria with Conformance level.
    options:
      -  1.1.1	Non-text Content	A
      -  1.2.1	Audio-only and Video-only (Pre-recorded)	A
      -  1.2.2	Captions (Pre-recorded)	A
      -  1.2.3	Audio Description or Media Alternative (Pre-recorded)	A
      -  1.2.4	Captions (Live)	AA
      -  1.2.5	Audio Description (Pre-recorded)	AA
      -  1.2.6	Sign Language (Pre-recorded)	AAA
      -  1.2.7	Extended Audio description (Pre-recorded)	AAA
      -  1.2.8	Media Alternative (Pre-recorded)	AAA
      -  1.2.9	Audio Only (Live)	AAA
      -  1.3.1	Info and Relationships	A
      -  1.3.2	Meaningful Sequence	A
      -  1.3.3	Sensory Characteristics	A
      -  1.3.4	Orientation (WCAG 2.1)	AA
      -  1.3.5	Identify Input Purpose (WCAG 2.1)	AA
      -  1.3.6	Identify Purpose (WCAG 2.1)	AAA
      -  1.4.1	Use of Colour	A
      -  1.4.2	Audio Control	A
      -  1.4.3	Contrast (Minimum)	AA
      -  1.4.4	Resize Text	AA
      -  1.4.5	Images of Text	AA
      -  1.4.6	Contrast (Enhanced)	AAA
      -  1.4.7	Low or No Background Audio	AAA
      -  1.4.8	Visual Presentation	AAA
      -  1.4.9	Images of Text (No Exception)	AAA
      -  1.4.10	Reflow (WCAG 2.1)	AA
      -  1.4.11	Non-Text Contrast  (WCAG 2.1)	AA
      -  1.4.12	Text Spacing  (WCAG 2.1)	AA
      -  1.4.13	Content on Hover or Focus  (WCAG 2.1)	AA
      -  2.1.1	Keyboard	A
      -  2.1.2	No Keyboard Trap	A
      -  2.1.3	Keyboard (No Exception)	AAA
      -  2.1.4	Character Key Shortcuts (WCAG 2.1)	A
      -  2.2.1	Timing Adjustable	A
      -  2.2.2	Pause, Stop, Hide	A
      -  2.2.3	No Timing	AAA
      -  2.2.4	Interruptions	AAA
      -  2.2.5	Re-authenticating	AAA
      -  2.2.6	Timeouts  (WCAG 2.1)	AAA
      -  2.3.1	Three Flashes or Below	A
      -  2.3.2	Three Flashes	AAA
      -  2.3.3	Animation from Interactions  (WCAG 2.1)	AAA
      -  2.4.1	Bypass Blocks	A
      -  2.4.10	Section Headings	AAA
      -  2.4.2	Page Titled	A
      -  2.4.3	Focus Order	A
      -  2.4.4	Link Purpose (In Context)	A
      -  2.4.5	Multiple Ways	AA
      -  2.4.6	Headings and Labels	AA
      -  2.4.7	Focus Visible	AA
      -  2.4.8	Location	AAA
      -  2.4.9	Link Purpose (Link Only)	AAA
      -  2.5.1	Pointer Gestures (WCAG 2.1)	A
      -  2.5.2	Pointer Cancellation  (WCAG 2.1)	A
      -  2.5.3	Label in Name (WCAG 2.1)	A
      -  2.5.4	Motion Actuation  (WCAG 2.1)	A
      -  2.5.5	Target Size (WCAG 2.1)	AAA
      -  2.5.6	Concurrent Input Mechanisms (WCAG 2.1)	AAA
      -  3.1.1	Language of Page	A
      -  3.1.2	Language of Parts	AA
      -  3.1.3	Unusual words	AAA
      -  3.1.4	Abbreviations	AAA
      -  3.1.5	Reading Level	AAA
      -  3.1.6	Pronunciation	AAA
      -  3.2.1	On Focus	A
      -  3.2.2	On Input	A
      -  3.2.3	Consistent Navigation	AA
      -  3.2.4	Consistent Identification	AA
      -  3.2.5	Change on Request	AAA
      -  3.3.1	Error Identification	A
      -  3.3.2	Labels or Instructions	A
      -  3.3.3	Error Suggestion	AA
      -  3.3.4	Error Prevention (Legal, Financial, Data)	AA
      -  3.3.5	Help	AAA
      -  3.3.6	Error Prevention (All)	AAA
      -  4.1.1	Parsing	A
      -  4.1.2	Name, Role, Value	A
      -  4.1.3	Status Messages (WCAG 2.1)	AA
  validations:
    required: true
- type: dropdown
  attributes:
    label: Devices
    multiple: true
    description: Select the device where you encountered the bug.
    options:
      -  Desktop
      -  iOS
      -  Android
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Issue Description
    placeholder: |
      A concise description of what you're experiencing.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: textarea
  attributes:
    label: Issue Impact
    placeholder: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Recommendation
    placeholder: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true


