name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ["Bug", "Needs Triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: dropdown
  attributes:
    label: Devices
    Multiple: true
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
      -  Desktop
      -  iOS
      -  Android
    
- type: textarea
  attributes:
    label: Issue Description
    description: |
      A concise description of what you're experiencing.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: textarea
  attributes:
    label: Issue Impact
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Recommendation
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true


